### ISSUE TITLE
Error at RedisSessionManager

### ISSUE THREAD

**Issue by zwnuance** [chexagon/redis-session-manager#1]
Hi, I put redis-session-manager-with-dependencies-2.0.3.jar into tomcat lib dir, but tomcat startup some error occur, Error Log:
 Unable to load serializer
java.lang.NoSuchMethodError: com.crimsonhexagon.rsm.RedisSessionManager.getContext()Lorg/apache/catalina/Context;
at com.crimsonhexagon.rsm.RedisSessionManager.getContainerClassLoader(RedisSessionManager.java:93)
at com.crimsonhexagon.rsm.redisson.SingleServerSessionManager.buildClient(SingleServerSessionManager.java:44)
    at com.crimsonhexagon.rsm.RedisSessionManager.startInternal(RedisSessionManager.java:111)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5540)

**Comment by scubasau** [comment]
What version of tomcat did this occur in?

**Comment by scubasau** [comment]
Closing old issues.

**Comment by lapygithub** [comment]
Not sure if it is good form to add to a closed Issue.
I'm getting this on Tomcat 7.0.85 with redis-session-manager-with-dependencies-2.2.1.jar

**Comment by lapygithub** [comment]
Thanks for the quick response.  I can validate that the same setup works in 8.0.x as I've just tried to move there and now back to 7.  Tried to keep this setup for AWS Elasticache.  Guess I'll have to see if the legacy version will work with Elasticache Redis.  Cheers.
